# Generated by Django 5.1.3 on 2024-11-29 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("item_desc", models.TextField(blank=True, null=True)),
                ("item_price", models.FloatField()),
                ("item_rating", models.FloatField(blank=True, default=0.0)),
                (
                    "item_img",
                    models.ImageField(default="default.jpg", upload_to="item_images"),
                ),
                ("date_added", models.DateField(editable=False)),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
