# Generated by Django 5.1.3 on 2024-11-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        ("login", "0002_delete_usermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="seller",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="login.account"
            ),
        ),
    ]
