# Generated by Django 5.1.3 on 2024-11-29 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_items_date_added_cart"),
        ("login", "0002_delete_usermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="login.account",
            ),
        ),
    ]
