# Generated by Django 5.1.3 on 2024-11-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_items_seller"),
    ]

    operations = [
        migrations.DeleteModel(name="Cart",),
    ]
