# Generated by Django 5.1.3 on 2024-11-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="items",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
